version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: kovon
    environment:
      POSTGRES_USER: kovon
      POSTGRES_PASSWORD: kovon123
      POSTGRES_DB: kovon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kovon"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: